version: '3.8'
services:
  php:
    build:
      context: .
      dockerfile: php.Dockerfile
    dns:
      - 8.8.8.8
      - 8.8.4.4
    container_name: php-container
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    ports:
      - "8000:80"
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: nginx-container
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  db:
    image: postgres:15
    container_name: postgres-container
    environment:
      POSTGRES_USER: wiam_user
      POSTGRES_PASSWORD: wiam_password
      POSTGRES_DB: WiamTest
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
